### PR TITLE
Unbreak build on FreeBSD

### PR DESCRIPTION
**Pull request by jbeich**
Regressed by 899843978ebd. Switching from Clang/libc++ to GCC/libstdc++ doesn't help. GNU libc also defines `basename` in `<string.h>` for OSF/1 compatibility. See also [POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/functions/basename.html).

Clang/libc++ 13.0.0:
```c++
src/main.cpp:7:17: error: use of undeclared identifier 'basename'
  string name = basename(argv[0]);
                ^
```

GCC/libstdc++ 11.2.0:
```c++
src/main.cpp: In function 'void showHelp(char**)':
src/main.cpp:7:17: error: 'basename' was not declared in this scope; did you mean 'rename'?
    7 |   string name = basename(argv[0]);
      |                 ^~~~~~~~
      |                 rename
```

### CODE REVIEW

**Comment by steinex** [comment]
#5 ;-)

**Comment by ErikReider** [comment]
Closing in favor of #5. Did you guys plan this? Your PRs were 10 mins apart :)
